version: '3.3'
services:
  db:
    container_name: elasticdb
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
  nodeserver:
    image: nodeserver
    build:
      context: .
      dockerfile: docker/node.dockerfile
    depends_on:
      - db
    ports:
      - 9229:9229
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
      - 9229
    volumes:
      - .:/var/www/nodeserver
      - /var/www/nodeserver/node_modules
    env_file:
      - .env
volumes:
  my-db:
